# -*- coding: utf-8 -*-
"""BioMistral_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRY5hYoepTKDLaw0fqi6uYaKS9wsGmet
"""

from transformers import AutoTokenizer, AutoModelForMaskedLM, Trainer, TrainingArguments
from datasets import Dataset
import pandas as pd

# Load the tokenizer and model
model_name = "emilyalsentzer/Bio_ClinicalBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForMaskedLM.from_pretrained(model_name)  # Ensure this is for masked LM

# Load your preprocessed dataset
df = pd.read_csv("Dataset/Preprocessed Data/processed_dataset.csv")

# Convert DataFrame to Hugging Face Dataset
dataset = Dataset.from_pandas(df)

# Tokenization function with labels for MLM
def tokenize_function(examples):
    texts = [str(text) for text in examples['transcription']]
    inputs = tokenizer(texts, padding='max_length', truncation=True, max_length=512)

    # MLM labels: set to -100 to ignore them
    inputs["labels"] = inputs.input_ids.copy()
    return inputs

# Tokenize the dataset
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Split the dataset into training and evaluation sets
train_test_split = tokenized_datasets.train_test_split(test_size=0.2)
train_dataset = train_test_split['train']
eval_dataset = train_test_split['test']

# Define the training arguments
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    logging_dir='./logs',
    evaluation_strategy="steps",  # Updated from deprecated `evaluation_strategy`
    save_total_limit=1,
    eval_steps=500,  # Evaluate every 500 steps
)

# Define the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,  # Provide the evaluation dataset here
    tokenizer=tokenizer
)

# Fine-tune the model
trainer.train()

# Save the Fine-Tuned Model
model.save_pretrained("./fine-tuned-biomistral")
tokenizer.save_pretrained("./fine-tuned-biomistral")
